# Generated by Django 5.0 on 2023-12-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='finish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(),
        ),
    ]
