# Generated by Django 5.0 on 2024-01-08 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0003_alter_course_finish_date_alter_course_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='course',
            new_name='courses',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_app.lesson'),
        ),
    ]
