# Generated by Django 5.0 on 2024-01-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0004_rename_course_catalog_courses_remove_lesson_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(default='main', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_app.catalog'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_app.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_app.teacher'),
        ),
    ]
