# Generated by Django 5.0 on 2024-01-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0005_remove_catalog_courses_remove_course_lessons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='catalog',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
