# Generated by Django 5.0 on 2024-01-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0008_user_alter_lesson_teacher_delete_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(null=True, to='learning_app.course'),
        ),
    ]
